#!/usr/bin/env python3
"""Generate the root BUCK file for the main noctalia executable."""

import re
import subprocess
import sys
from pathlib import Path

PKG_LIBS = [
    "sdbus-c++", "wayland-client", "wayland-egl", "freetype2", "fontconfig",
    "cairo", "pango", "pangocairo", "pangoft2", "harfbuzz", "librsvg-2.0",
    "xkbcommon", "glib-2.0", "gobject-2.0", "gio-2.0",
    "polkit-agent-1", "polkit-gobject-1", "libpipewire-0.3", "wireplumber-0.5",
    "libcurl", "libqalculate", "libxml-2.0", "md4c", "libwebp", "pam",
    "egl", "glesv2",
]


def extract_sources(meson_path: Path) -> list[str]:
    text = meson_path.read_text()
    m = re.search(r"_noctalia_sources\s*=\s*files\((.*?)\)", text, re.DOTALL)
    if not m:
        raise RuntimeError("Could not find _noctalia_sources in meson.build")
    return re.findall(r"'([^']+\.cpp)'", m.group(1))


def git_revision() -> str:
    try:
        return subprocess.check_output(
            ["git", "describe", "--tags", "--always", "--dirty=-dirty", "--abbrev=12"],
            text=True, stderr=subprocess.DEVNULL,
        ).strip()
    except Exception:
        return "unknown"


def pkg_libs() -> str:
    libs = set()
    for pc in PKG_LIBS:
        try:
            out = subprocess.check_output(
                ["pkg-config", "--libs-only-l", pc], text=True, stderr=subprocess.DEVNULL
            )
            for lib in out.strip().split():
                if lib.startswith("-l"):
                    libs.add(lib)
        except subprocess.CalledProcessError:
            pass
    return ",\n        ".join(f'"{l}"' for l in sorted(libs))


def define(name: str, value: str) -> str:
    return f'        "-D{name}=\\"{value}\\""'


def generate() -> str:
    sources = extract_sources(Path("meson.build"))
    revision = git_revision()
    linker_flags = pkg_libs()

    lines = [
        "# Generated by tools/generate_buck2_noctalia.py",
        "# Do not edit by hand; rerun the generator after source changes.",
        "",
        "export_file(",
        '    name = "git_revision_h_in",',
        '    src = "src/core/git_revision.h.in",',
        '    visibility = ["PUBLIC"],',
        ")",
        "",
        "genrule(",
        '    name = "git_revision_header",',
        '    srcs = [":git_revision_h_in"],',
        '    out = "noctalia_git_revision.h",',
        f'    cmd = "sed -e \\"s/@VCS_TAG@/{revision}/g\\" $(location :git_revision_h_in) > $OUT",',
        ")",
        "",
        "cxx_binary(",
        '    name = "noctalia",',
        "    srcs = [",
    ]
    for s in sources:
        lines.append(f'        "{s}",')
    lines += [
        "    ],",
        '    headers = [":git_revision_header"],',
        "    include_directories = [",
        '        "src",',
        '        "third_party/wuffs",',
        '        ".",',
        "    ],",
        "    compiler_flags = [",
        '        "-Ithird_party/wuffs",',
        '        "-Isrc",',
        '        "-I.",',
        define("NOCTALIA_SOURCE_ASSETS_DIR", "assets") + ",",
        define("NOCTALIA_INSTALL_PREFIX", "/usr/local") + ",",
        define("NOCTALIA_INSTALL_DATADIR", "share") + ",",
        define("NOCTALIA_VERSION", "5.0.0") + ",",
        "    ],",
        "    linker_flags = [",
        f"        {linker_flags},",
        "    ],",
        "    deps = [",
        '        "//third_party/dr_wav:dr_wav",',
        '        "//third_party/fzy:fzy",',
        '        "//third_party/luau:luau",',
        '        "//third_party/material_color_utilities:material_color_utilities",',
        '        "//third_party/system:sdbus_cpp",',
        '        "//third_party/system:wayland_client",',
        '        "//third_party/system:wayland_egl",',
        '        "//third_party/system:freetype2",',
        '        "//third_party/system:fontconfig",',
        '        "//third_party/system:cairo",',
        '        "//third_party/system:cairo_ft",',
        '        "//third_party/system:pango",',
        '        "//third_party/system:pangocairo",',
        '        "//third_party/system:pangoft2",',
        '        "//third_party/system:harfbuzz",',
        '        "//third_party/system:librsvg",',
        '        "//third_party/system:xkbcommon",',
        '        "//third_party/system:glib",',
        '        "//third_party/system:gobject",',
        '        "//third_party/system:gio",',
        '        "//third_party/system:polkit_agent",',
        '        "//third_party/system:polkit_gobject",',
        '        "//third_party/system:pipewire",',
        '        "//third_party/system:wireplumber",',
        '        "//third_party/system:curl",',
        '        "//third_party/system:libqalculate",',
        '        "//third_party/system:libxml2",',
        '        "//third_party/system:md4c",',
        '        "//third_party/system:nlohmann_json",',
        '        "//third_party/system:tomlplusplus",',
        '        "//third_party/system:libwebp",',
        '        "//third_party/system:egl",',
        '        "//third_party/system:gles2",',
        '        "//third_party/system:pam",',
        '        "//protocols:xdg-output-unstable-v1",',
        '        "//protocols:xdg-shell",',
        '        "//protocols:ext-workspace-v1",',
        '        "//protocols:ext-foreign-toplevel-list-v1",',
        '        "//protocols:ext-data-control-v1",',
        '        "//protocols:xdg-activation-v1",',
        '        "//protocols:ext-session-lock-v1",',
        '        "//protocols:ext-idle-notify-v1",',
        '        "//protocols:ext-background-effect-v1",',
        '        "//protocols:fractional-scale-v1",',
        '        "//protocols:viewporter",',
        '        "//protocols:idle-inhibit-unstable-v1",',
        '        "//protocols:text-input-unstable-v3",',
        '        "//protocols:virtual-keyboard-unstable-v1",',
        '        "//protocols:dwl-ipc-unstable-v2",',
        '        "//protocols:org-kde-plasma-virtual-desktop",',
        '        "//protocols:cursor-shape-v1",',
        '        "//protocols:wlr-foreign-toplevel-management-unstable-v1",',
        '        "//protocols:wlr-data-control-unstable-v1",',
        '        "//protocols:hyprland-focus-grab-v1",',
        '        "//protocols:hyprland-toplevel-mapping-v1",',
        '        "//protocols:wlr-gamma-control-unstable-v1",',
        '        "//protocols:wlr-screencopy-unstable-v1",',
        '        "//protocols:wlr-layer-shell-unstable-v1",',
        "    ],",
        '    visibility = ["PUBLIC"],',
        ")",
        "",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    out = Path("BUCK")
    out.write_text(generate())
    print(f"Generated {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
