#!/usr/bin/env python3
"""Generate buck2 BUILD files for system dependencies and Wayland protocols.

Run this inside the Noctalia nix devshell (or any environment where all
pkg-config files listed below are on PKG_CONFIG_PATH).
"""

import shlex
import subprocess
import sys
from pathlib import Path

# Each entry: (target_name, pkg_config_name)
DEPS = [
    ("sdbus_cpp", "sdbus-c++"),
    ("wayland_client", "wayland-client"),
    ("wayland_protocols", "wayland-protocols"),
    ("wayland_egl", "wayland-egl"),
    ("freetype2", "freetype2"),
    ("fontconfig", "fontconfig"),
    ("cairo", "cairo"),
    ("cairo_ft", "cairo-ft"),
    ("pango", "pango"),
    ("pangocairo", "pangocairo"),
    ("pangoft2", "pangoft2"),
    ("harfbuzz", "harfbuzz"),
    ("librsvg", "librsvg-2.0"),
    ("xkbcommon", "xkbcommon"),
    ("glib", "glib-2.0"),
    ("gobject", "gobject-2.0"),
    ("gio", "gio-2.0"),
    ("polkit_agent", "polkit-agent-1"),
    ("polkit_gobject", "polkit-gobject-1"),
    ("pipewire", "libpipewire-0.3"),
    ("wireplumber", "wireplumber-0.5"),
    ("curl", "libcurl"),
    ("libqalculate", "libqalculate"),
    ("libxml2", "libxml-2.0"),
    ("md4c", "md4c"),
    ("nlohmann_json", "nlohmann_json"),
    ("tomlplusplus", "tomlplusplus"),
    ("libwebp", "libwebp"),
    ("jemalloc", "jemalloc"),
    ("egl", "egl"),
    ("gles2", "glesv2"),
    ("epoxy", "epoxy"),
    ("pam", "pam"),
]

# Protocols from the system wayland-protocols package.
SYSTEM_PROTOCOLS = [
    ("xdg-output-unstable-v1", "unstable/xdg-output/xdg-output-unstable-v1.xml"),
    ("xdg-shell", "stable/xdg-shell/xdg-shell.xml"),
    ("ext-workspace-v1", "staging/ext-workspace/ext-workspace-v1.xml"),
    ("ext-foreign-toplevel-list-v1", "staging/ext-foreign-toplevel-list/ext-foreign-toplevel-list-v1.xml"),
    ("ext-data-control-v1", "staging/ext-data-control/ext-data-control-v1.xml"),
    ("xdg-activation-v1", "staging/xdg-activation/xdg-activation-v1.xml"),
    ("ext-session-lock-v1", "staging/ext-session-lock/ext-session-lock-v1.xml"),
    ("ext-idle-notify-v1", "staging/ext-idle-notify/ext-idle-notify-v1.xml"),
    ("ext-background-effect-v1", "staging/ext-background-effect/ext-background-effect-v1.xml"),
    ("fractional-scale-v1", "staging/fractional-scale/fractional-scale-v1.xml"),
    ("viewporter", "stable/viewporter/viewporter.xml"),
    ("idle-inhibit-unstable-v1", "unstable/idle-inhibit/idle-inhibit-unstable-v1.xml"),
]

# Project-local protocols in protocols/.
LOCAL_PROTOCOLS = [
    "text-input-unstable-v3",
    "virtual-keyboard-unstable-v1",
    "dwl-ipc-unstable-v2",
    "org-kde-plasma-virtual-desktop",
    "cursor-shape-v1",
    "wlr-foreign-toplevel-management-unstable-v1",
    "wlr-data-control-unstable-v1",
    "hyprland-focus-grab-v1",
    "hyprland-toplevel-mapping-v1",
    "wlr-gamma-control-unstable-v1",
    "wlr-screencopy-unstable-v1",
]


def pkg_config(name: str, what: str) -> list[str]:
    try:
        out = subprocess.check_output(
            ["pkg-config", what, name], text=True, stderr=subprocess.DEVNULL
        )
    except subprocess.CalledProcessError as e:
        print(f"warning: pkg-config {what} {name} failed: {e}", file=sys.stderr)
        return []
    return shlex.split(out.strip())


def pkg_config_var(name: str, var: str) -> str | None:
    try:
        out = subprocess.check_output(
            ["pkg-config", "--variable=" + var, name], text=True, stderr=subprocess.DEVNULL
        )
    except subprocess.CalledProcessError as e:
        print(f"warning: pkg-config --variable={var} {name} failed: {e}", file=sys.stderr)
        return None
    out = out.strip()
    if out.startswith("//"):
        out = out[1:]
    return out


def split_flags(flags: list[str]) -> tuple[list[str], list[str]]:
    pp = []
    link = []
    it = iter(flags)
    for f in it:
        if f.startswith(("-I", "-D", "-U")):
            pp.append(f)
        elif f in ("-pthread",):
            pp.append(f)
            link.append(f)
        elif f == "-framework":
            link.append(f)
            link.append(next(it))
        elif f.startswith("-framework:"):
            link.append(f)
        elif f.startswith("-Wl,"):
            link.append(f)
        elif f.startswith("-l"):
            link.append(f)
        elif f.startswith("-L"):
            link.append(f)
        elif f.startswith("-std="):
            pass
        elif f in ("-DTOML_HEADER_ONLY=0", "-DTOML_SHARED_LIB=1"):
            pp.append(f)
        else:
            pp.append(f)
            link.append(f)
    return pp, link


def generate_system_deps() -> str:
    lines = [
        "# Generated by tools/generate_buck2_system_deps.py",
        "# Do not edit by hand; rerun the generator after dependency changes.",
        "",
        "load(\"//build_defs:noctalia.bzl\", \"system_cxx_library\")",
        "",
    ]

    for target, pc_name in DEPS:
        cflags = pkg_config(pc_name, "--cflags")
        libs = pkg_config(pc_name, "--libs")
        pp, link = split_flags(cflags + libs)
        lines.append(f"system_cxx_library(")
        lines.append(f"    name = \"{target}\",")
        lines.append(f"    pkg_config = \"{pc_name}\",")
        if pp:
            lines.append(f"    exported_preprocessor_flags = {pp},")
        if link:
            lines.append(f"    exported_linker_flags = {link},")
        lines.append(f"    visibility = [\"PUBLIC\"],")
        lines.append(")")
        lines.append("")

    return "\n".join(lines) + "\n"


def generate_protocols() -> str:
    protos_dir = pkg_config_var("wayland-protocols", "pkgdatadir")
    if protos_dir is None:
        protos_dir = ""

    lines = [
        "# Generated by tools/generate_buck2_system_deps.py",
        "# Do not edit by hand; rerun the generator after dependency changes.",
        "",
        "load(\"//build_defs:noctalia.bzl\", \"wayland_protocol_library\")",
        "",
    ]

    for target, rel_path in SYSTEM_PROTOCOLS:
        xml = protos_dir + "/" + rel_path if protos_dir else rel_path
        lines.append(f"wayland_protocol_library(")
        lines.append(f"    name = \"{target}\",")
        lines.append(f"    xml = \"{xml}\",")
        lines.append(f"    visibility = [\"PUBLIC\"],")
        lines.append(")")
        lines.append("")

    for name in LOCAL_PROTOCOLS:
        xml_target = name.replace("-", "_") + "_xml"
        lines.append("export_file(")
        lines.append(f"    name = \"{xml_target}\",")
        lines.append(f"    src = \"{name}.xml\",")
        lines.append(f"    visibility = [\"PUBLIC\"],")
        lines.append(")")
        lines.append("")
        lines.append(f"wayland_protocol_library(")
        lines.append(f"    name = \"{name}\",")
        lines.append(f"    xml = \":{xml_target}\",")
        lines.append(f"    visibility = [\"PUBLIC\"],")
        lines.append(")")
        lines.append("")

    # Special handling for wlr-layer-shell: rename namespace -> name_space.
    lines.append("export_file(")
    lines.append('    name = "wlr_layer_shell_unstable_v1_xml",')
    lines.append('    src = "wlr-layer-shell-unstable-v1.xml",')
    lines.append('    visibility = ["PUBLIC"],')
    lines.append(")")
    lines.append("")
    lines.append("genrule(")
    lines.append('    name = "wlr_layer_shell_unstable_v1_header",')
    lines.append('    srcs = [":wlr_layer_shell_unstable_v1_xml"],')
    lines.append('    out = "wlr-layer-shell-unstable-v1-client-protocol.h",')
    lines.append('    cmd = "wayland-scanner client-header $(location :wlr_layer_shell_unstable_v1_xml) $OUT && sed -i.bak s/namespace/name_space/g $OUT",')
    lines.append(")")
    lines.append("")
    lines.append("genrule(")
    lines.append('    name = "wlr_layer_shell_unstable_v1_source",')
    lines.append('    srcs = [":wlr_layer_shell_unstable_v1_xml"],')
    lines.append('    out = "wlr-layer-shell-unstable-v1-client-protocol.c",')
    lines.append('    cmd = "wayland-scanner private-code $(location :wlr_layer_shell_unstable_v1_xml) $OUT",')
    lines.append(")")
    lines.append("")
    lines.append("cxx_library(")
    lines.append('    name = "wlr-layer-shell-unstable-v1",')
    lines.append('    srcs = [":wlr_layer_shell_unstable_v1_source"],')
    lines.append('    exported_headers = [":wlr_layer_shell_unstable_v1_header"],')
    lines.append('    header_namespace = "",')
    lines.append('    preferred_linkage = "static",')
    lines.append('    link_whole = True,')
    lines.append('    visibility = ["PUBLIC"],')
    lines.append('    within_view = ["PUBLIC"],')
    lines.append(")")
    lines.append("")

    return "\n".join(lines) + "\n"


def main() -> int:
    system_out = Path("third_party/system/BUCK")
    system_out.parent.mkdir(parents=True, exist_ok=True)
    system_out.write_text(generate_system_deps())
    print(f"Generated {system_out}")

    protocols_out = Path("protocols/BUCK")
    protocols_out.write_text(generate_protocols())
    print(f"Generated {protocols_out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
